### PR TITLE
enhance `TimedJSONWebSignatureSerializer` to support never-expire

### PR DESCRIPTION
**Pull request by RussellLuo**
Motivation
-------------

In `itsdangerous`, you can generate tokens without expiry time based on `JSONWebSignatureSerializer`:

    from itsdangerous import JSONWebSignatureSerializer as JWSSerializer

    def make_normal_token(secret_key, data):
        s = JWSSerializer(secret_key)
        return s.dumps(data)

and you can generate tokens with expiry time based on `TimedJSONWebSignatureSerializer`:

    from itsdangerous import TimedJSONWebSignatureSerializer as TimedJWSSerializer

    def make_timed_token(secret_key, data, expires=None):
        s = TimedJWSSerializer(secret_key, expires_in=expires)
        return s.dumps(data)

Then, you can merge the above two functions as one:

    from itsdangerous import JSONWebSignatureSerializer as JWSSerializer
    from itsdangerous import TimedJSONWebSignatureSerializer as TimedJWSSerializer

    def make_token(secret_key, data, expires=None):
        if expires == 0:
            s = JWSSerializer(secret_key)
        else:
            s = TimedJWSSerializer(secret_key, expires_in=expires)
        return s.dumps(data)

But there's no easy way (neither `JSONWebSignatureSerializer.loads()` nor `TimedJSONWebSignatureSerializer.loads()`) to load tokens generated by `make_token`. (Maybe any suggestions?)

    def load_token(secret_key, token):
        pass  # how to load?

Advantage
-------------

With the enhanced version of `TimedJSONWebSignatureSerializer`, everything above can be implemented as follows:

    from itsdangerous import TimedJSONWebSignatureSerializer as TimedJWSSerializer

    def make_token(secret_key, data, expires=None):
        s = TimedJWSSerializer(secret_key, expires_in=expires)
        return s.dumps(data)

    def load_data(secret_key, token):
        s = TimedJWSSerializer(secret_key)
        try:
            data = s.loads(token)
            return data
        except SignatureExpired:  # valid token, but expired
            return None
        except BadSignature:  # invalid token
            return None

### CODE REVIEW

**Comment by itmard** [comment]
@mitsuhiko Why you don't merge this /? Is there any security problem ?

**Comment by spinus** [comment]
@itmard probably because of #56

**Comment by mitsuhiko** [comment]
Pretty much, yes.  If someone wants to have feature development happen here it would need someone to take over that work.

**Comment by davidism** [comment]
> The "exp" (expiration time) claim identifies the expiration time on or after which the JWT MUST NOT be accepted for processing.

This would go against the JWT spec (although we're admittedly implementing JWS with extra headers, not JWT).  Instead, either try loading with `JSONWebSignature` if `TimedJSONWebSignature` raises `BadSignature`, or always load using `JSONWebSignature` and validate the header yourself.

**Pull request closed without merging**
