### PR TITLE
pin requirements

### PR DESCRIPTION
**Pull request by davidism**
Use [pip-tools](https://github.com/jazzband/pip-tools) to pin dependencies. Use [pip-compile-multi](https://github.com/peterdemin/pip-compile-multi) to automate it. Adding these allows a service like Dependabot to make automatic upgrade PRs and ensures random upgrades won't cause confusing test failures for contributors later. I don't think that's a particular issue for this specific project any time recently, but I want to do this consistently for all the projects.

To install for dev, you'd now do `pip install -e . -r requirements/dev.txt`, which pulls in the test and docs requirements as well as tox and pre-commit. (You could skip `dev.txt` if you have tox and pre-commit installed globally with pipx.) ReadTheDocs is configured to use `requirements/docs.txt` (it was using `docs/requirements.txt` which was manually pinning dependencies before). Tox is configured to use `requirements/tests.txt`.

### CODE REVIEW

**Comment by peterdemin** [comment]
If I understand correctly, Dependabot doesn't support `-r` references well. When it opens PRs to upgrade just a single package in dev.txt, it'll also bring all the transient dependencies, that might already be in one of the referenced files. I don't know if there was any progress in this direction though, my observations are from several months ago.

**Comment by davidism** [comment]
:-( You're right: https://github.com/pallets/secure-cookie/pull/16/files It wiped out what `pip-compile-multi` did. Presumably it's using `pip-compile directly` instead?

**Comment by peterdemin** [comment]
I asked the author to add support for references. Would you like to chime in?

**Comment by davidism** [comment]
Yeah, link any pip-tools or Dependabot tracking issues.

**Comment by peterdemin** [comment]
Here's the issue: https://github.com/dependabot/dependabot-core/issues/536

**Comment by davidism** [comment]
Do you have a recommendation for now? Use pip-compile (and their pre-commit hooks)? Use a different upgrade service?

**Comment by davidism** [comment]
Perhaps request a flag in pip-compile to leave `-r` and have Dependabot use the flag if it sees those lines.

Or add a flag to pip-compile-multi to output files like pip-compile instead of keeping `-r`.

**Comment by peterdemin** [comment]
I think it's best if Dependabot uses pip-compile-multi when it detects `-r` in lock files.

**Pull request merged**
