### PR TITLE
Change reversed() to [::-1] for speed

### PR DESCRIPTION
**Pull request by scragg0x**

### CODE REVIEW

**Comment by jeffwidman** [comment]
I haven't dug deeply into the code, but skimming your PR made me curious... `[::-1]` only replaces `reversed()`. Why did you drop the `''.join()` from your version?

**Comment by scragg0x** [comment]
Ahh, such an old commit of mine. It would appear that I just neglected it. Good thing this wasn't pulled.

**Comment by ThiefMaster** [comment]
The join is not needed with that syntax:

```
>>> ''.join(reversed('foo'))
'oof'
>>> 'foo'[::-1]
'oof'
```

`reversed` returns an iterator while `[::-1]` already returns the reversed string

**Comment by davidism** [comment]
I timed both versions and there was no significant change, so just going to close this and leave it as is.

**Comment by scragg0x** [comment]
https://gist.github.com/scragg0x/97d2927ce20b0766710bcee43795c2a2

Interestingly, I just did a bench and reversed it much faster anyway with larger lists.  25x faster when using the example gist.

**Comment by ThiefMaster** [comment]
That benchmark is incorrect - `reversed()` doesn't actually reverse anything; it just provides an iterator that starts at the end of the collection

**Comment by scragg0x** [comment]
@ThiefMaster I see, thanks for clarifying. I figured I missed something to have such a large disparity.

**Comment by jeffwidman** [comment]
Now that I understand what's happening here, I'd vote to merge this.

**Comment by davidism** [comment]
After a (very silly) discussion about this micro-optimization, http://chat.stackoverflow.com/transcript/message/29868921#29868921, it looks like it would be better to replace the whole thing with

~~~python
to_int64 = struct.Struct('>Q').pack

def int_to_bytes(num):
    return to_int64(num).lstrip(b'\x00')
~~~

**Comment by davidism** [comment]
090e9e2d8fad6b6db302244721cce2981d43abf3

**Pull request closed without merging**
