### PR TITLE
Infer algorithm from header.

### PR DESCRIPTION
**Pull request by tyan-boot**
Algorithm should be inferred from jwt header when load token.

### CODE REVIEW

**Comment by davidism** [comment]
From the code you've removed, it seems pretty deliberate that we don't allow arbitrary algorithms. I'm not entirely familiar with JWT (and note that itsdangerous is JWS), but I remember there being an issue with insecure algorithms. You should configure your signer with the algorithm you expect. You can also use your own signer subclass that does this, if you're willing to take that risk.

**Comment by tyan-boot** [comment]
@davidism `self.make_algorithm` will check it.

**Comment by ThiefMaster** [comment]
Without looking closer at the code: Getting the algorithm from user-provided data sounds dangerous. I remember a few sites got pwned because one could sent a JWT with a null algorithm...

**Comment by davidism** [comment]
Probably related to https://github.com/pallets/itsdangerous/issues/54.

The way I interpret the current code is that we only support the algorithm that the signer is configured with, rather than allowing the client to dictate what we should do. I don't think that's an unreasonable way to do things, especially since that's how the regular itsdangerous signers work.

**Comment by davidism** [comment]
I'm not even clear how a client would produce a valid signature with a different algorithm, given that they wouldn't have the secret key. But again, I'm not really familiar with JWS.

**Comment by davidism** [comment]
From Armin on Discord https://discordapp.com/channels/531221516914917387/531221927071711255/562733914301399090:

> using the alg header is unsafe
> the existing code is intentional
> we cannot trust client data
> you can easily produce matching signatures if you have a wider set of algorithsm
> in particular there is a plaintext one too

**Pull request closed without merging**
