### PR TITLE
Replace all base64 decoding errors with BadData.

### PR DESCRIPTION
**Pull request by lucian1900**
Perhaps Exception is not the best thing to catch.

### CODE REVIEW

**Comment by davidism** [comment]
I'm on board with the exception fix, but why is there an unrelated change that makes invalid data into valid tokens?

**Comment by lucian1900** [comment]
It's not unrelated, but I guess the PR's name implies a smaller scope.

Characters that are invalid base64 are first ignored, then decoding proceeds. Decoding could still fail because of bad data, though.

**Comment by davidism** [comment]
Yeah, but that's not something that should happen.  Invalid data is invalid, the fact that removing some characters might produces a valid signature doesn't matter.

**Comment by davidism** [comment]
Rebased with just the exception handling in ec69312709b42add477a6c00131c3d2155b2fe23.

**Pull request closed without merging**
